sudo: required

branches:
  only:
    - master

matrix:
  include:
    - dist: trusty
      language: python
      services:
        - docker
      script:
        - ./build_and_check_linux_wheels.sh
    - os: osx
      osx_image: xcode8.3
      script:
        - ./build_mac_os_x_wheels.sh

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then ./install_osx.sh; fi

notifications:
  recipients:
    - jb@sqreen.io
    - selim@sqreen.io
