trigger:
- master

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
   - task: UsePythonVersion@0
     inputs:
       versionSpec: '3.6'
       architecture: x64
   - checkout: self
   - bash: python setup.py sdist --dist-dir wheelhouse
   - template: helpers/release.yml
- job: mac
  pool: {vmImage: 'macOS-10.13'}
  steps:
   - checkout: self
   - template: helpers/release.yml
- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  steps:
   - script: git config --global core.symlinks true
   - checkout: self
   - powershell: |
       Remove-Item C:\ProgramData\Chocolatey\bin\python2.7.exe -force
       Remove-Item C:\ProgramData\Chocolatey\bin\python2.exe -force
     displayName: Remove extraneous Python Interpreters
   - template: helpers/release.yml
- job: fetch-sources-for-alpine
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
   - task: UsePythonVersion@0
     inputs:
       versionSpec: '2.7'
       architecture: x64
   - checkout: self
   - bash: python setup.py build_ext --no-build --no-sysroot
   - publish: py_mini_racer/extensions/v8
     artifact: sources-for-alpine
- job: alpine
  dependsOn:
   - fetch-sources-for-alpine
  container: nicolassqreen/azure-pipelines-container-alpine-python:latest
  steps:
   - checkout: self
   - download: current
     artifact: sources-for-alpine
   - bash: python setup.py build_ext --no-sysroot
