trigger:
- master

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
   - task: UsePythonVersion@0
     inputs:
       versionSpec: '3.6'
       architecture: x64
   - checkout: self
   - bash: python setup.py sdist --dist-dir wheelhouse
   - template: helpers/release.yml
- job: mac
  pool: {vmImage: 'macOS-10.13'}
  steps:
   - bash: sudo xcode-select -s /Applications/Xcode_8.3.3.app/Contents/Developer
   - checkout: self
   - template: helpers/release.yml
- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  steps:
   - checkout: self
   - script: |
       call C:\Program Files (x86)\Microsoft Visual Studio\2015\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x64
   - powershell: |
       Remove-Item C:\ProgramData\Chocolatey\bin\python2.7.exe -force
       Remove-Item C:\ProgramData\Chocolatey\bin\python2.exe -force
     displayName: Remove extraneous Python Interpreters
   - template: helpers/release.yml
