trigger:
- master

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
   - task: UsePythonVersion@0
     inputs:
       versionSpec: '3.6'
       architecture: x64
   - checkout: self
   - bash: python setup.py sdist --dist-dir wheelhouse
   - template: helpers/release.yml
- job: mac
  pool: {vmImage: 'macOS-10.13'}
  steps:
   - checkout: self
   - template: helpers/release.yml
- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  steps:
   - script: git config --global core.symlinks true
   - checkout: self
   - powershell: |
       Remove-Item C:\ProgramData\Chocolatey\bin\python2.7.exe -force
       Remove-Item C:\ProgramData\Chocolatey\bin\python2.exe -force
     displayName: Remove extraneous Python Interpreters
   - template: helpers/release.yml
- job: fetch_sources_for_alpine
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
   - task: UsePythonVersion@0
     inputs:
       versionSpec: '2.7'
       architecture: x64
   - checkout: self
   - bash: python py_mini_racer/extension/v8_build.py --no-build --no-sysroot
   - bash: tar -cf v8.tar py_mini_racer/extension/v8
   - publish: v8.tar
     artifact: sources-for-alpine
- job: alpine
  dependsOn:
   - fetch_sources_for_alpine
  container: nicolassqreen/azure-pipelines-container-alpine-python:latest
  steps:
   - checkout: self
   - download: current
     artifact: sources-for-alpine
   - bash: tar -xf v8.tar
   - bash: python py_mini_racer/extension/v8_build.py --no-update --no-sysroot
